-- liquibase formatted sql

-- changeset olha:1
CREATE TABLE IF NOT EXISTS notification_task
(
id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id           BIGINT NOT NULL,
message           TEXT NOT NULL,
date_and_time     TIMESTAMP NOT NULL
);